import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { colors } from "@/styles/colors";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"]
});

export const metadata = {
  title: "Maker Match",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cormorant.variable} suppressHydrationWarning>
      <body suppressHydrationWarning style={{ backgroundColor: colors.bgClr }}>
        {children}
      </body>
    </html>
  );
}
